<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2024-03-07">

<title>my_blog - Exercices - Semaine 3️⃣</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">my_blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/ameldhmn" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Exercices - Semaine 3️⃣</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">code</div>
                <div class="quarto-category">analysis</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">March 7, 2024</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="exercices---semaine-3" class="level2">
<h2 class="anchored" data-anchor-id="exercices---semaine-3">Exercices - Semaine 3</h2>
<section id="préparation." class="level3">
<h3 class="anchored" data-anchor-id="préparation.">Préparation.</h3>
<div style="text-align: justify;">
<p>Démarrez un nouveau projet rstudio intitulé TP3. Nous allons avoir besoin de plusieurs librairies aujourd’hui. Installez les en utilisant la commande suivante:</p>
<p>install.packages(c(“stringr”, “lubridate”, “arrow”, “dplyr”, “tidyr”, “jsonlite”, “RSQLite”))</p>
<p>À la racine du projet, créez un dossier data. Téléchargez les données associées au TP3 et décompressez les dans le dossier data. Supprimez le fichier .zip.</p>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(c("stringr", "lubridate", "arrow", "dplyr", "tidyr", "jsonlite", "RSQLite"))</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(arrow)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jsonlite)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RSQLite)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="exercice" class="level3">
<h3 class="anchored" data-anchor-id="exercice">Exercice</h3>
</section>
<section id="import-et-lecture-des-données" class="level3">
<h3 class="anchored" data-anchor-id="import-et-lecture-des-données">Import et lecture des données</h3>
</section>
<section id="question-1" class="level3">
<h3 class="anchored" data-anchor-id="question-1">Question 1</h3>
<section id="listez-les-fichiers-présents-dans-le-dossier-data.-quelles-sont-les-extensions-des-différents-fichiers" class="level4">
<h4 class="anchored" data-anchor-id="listez-les-fichiers-présents-dans-le-dossier-data.-quelles-sont-les-extensions-des-différents-fichiers">Listez les fichiers présents dans le dossier data. Quelles sont les extensions des différents fichiers ?</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">list.files</span>(<span class="st">"data"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>character(0)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>extensions <span class="ot">&lt;-</span> tools<span class="sc">::</span><span class="fu">file_ext</span>(data)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(extensions)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>logical(0)</code></pre>
</div>
</div>
<p>Il y a 3 fichiers dans le dossier data dont un sous format sqlite, un autre json et le dernier parquet.</p>
</section>
</section>
<section id="question-2" class="level3">
<h3 class="anchored" data-anchor-id="question-2">Question 2</h3>
<section id="lisez-le-fichier-.parquet-en-utilisant-la-librairie-arrow.-quelles-sont-les-dimensions-de-la-table-quelles-sont-les-colonnes-présentes" class="level4">
<h4 class="anchored" data-anchor-id="lisez-le-fichier-.parquet-en-utilisant-la-librairie-arrow.-quelles-sont-les-dimensions-de-la-table-quelles-sont-les-colonnes-présentes">Lisez le fichier .parquet en utilisant la librairie arrow. Quelles sont les dimensions de la table ? Quelles sont les colonnes présentes ?</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>tokyo <span class="ot">&lt;-</span> <span class="fu">read_parquet</span>(<span class="st">"~/Library/Mobile Documents/com~apple~CloudDocs/M1 ECAP/R avancé/data/tokyo_athletes.parquet"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(tokyo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11085     3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(tokyo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Name               NOC             Discipline       
 Length:11085       Length:11085       Length:11085      
 Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character  </code></pre>
</div>
</div>
<p>La table Tokyo compte 11 085 entrées et est structurée en 3 colonnes.</p>
<p>Les 3 colonnes présentes sont : Name, NOC et Discipline.</p>
</section>
</section>
<section id="question-3" class="level3">
<h3 class="anchored" data-anchor-id="question-3">Question 3</h3>
<section id="lisez-le-fichier-.json-en-utilisant-la-librairie-jsonlite.-quelles-sont-les-dimensions-de-la-table-quelles-sont-les-colonnes-présentes" class="level4">
<h4 class="anchored" data-anchor-id="lisez-le-fichier-.json-en-utilisant-la-librairie-jsonlite.-quelles-sont-les-dimensions-de-la-table-quelles-sont-les-colonnes-présentes">Lisez le fichier .json en utilisant la librairie jsonlite. Quelles sont les dimensions de la table ? Quelles sont les colonnes présentes ?</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>olympics <span class="ot">&lt;-</span> <span class="fu">read_json</span>(<span class="st">"~/Library/Mobile Documents/com~apple~CloudDocs/M1 ECAP/R avancé/data/olympics_athletes.json"</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(olympics)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>NULL</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#str(olympics)</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(olympics)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>NULL</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(olympics)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 269731</code></pre>
</div>
</div>
<p>Il y a un total de 269 731 éléments dans l’objet “olympics”.</p>
<p>Les colonnes présentes sont les suivantes :<br>
</p>
<ul>
<li><p>ID</p></li>
<li><p>Name</p></li>
<li><p>Sex</p></li>
<li><p>Age</p></li>
<li><p>Height</p></li>
<li><p>Weight</p></li>
<li><p>Team</p></li>
<li><p>NOC</p></li>
<li><p>Games</p></li>
<li><p>City</p></li>
<li><p>Sport</p></li>
<li><p>Event</p></li>
<li><p>Medal</p></li>
</ul>
</section>
</section>
<section id="question-4" class="level3">
<h3 class="anchored" data-anchor-id="question-4">Question 4</h3>
<section id="importez-la-librairie-rsqlite-et-ouvrez-une-connexion-à-la-base-de-données-sqlite-en-utilisant-la-fonction-dbconnect.-le-driver-à-utiliser-sera-sqlite.-quelles-sont-les-tables-présentes-dans-la-table-vous-pourrez-utiliser-la-fonction-dblisttables." class="level4">
<h4 class="anchored" data-anchor-id="importez-la-librairie-rsqlite-et-ouvrez-une-connexion-à-la-base-de-données-sqlite-en-utilisant-la-fonction-dbconnect.-le-driver-à-utiliser-sera-sqlite.-quelles-sont-les-tables-présentes-dans-la-table-vous-pourrez-utiliser-la-fonction-dblisttables.">Importez la librairie RSQLite, et ouvrez une connexion à la base de données sqlite en utilisant la fonction dbConnect. Le driver à utiliser sera SQLite(). Quelles sont les tables présentes dans la table ? Vous pourrez utiliser la fonction dbListTables.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>connexion <span class="ot">&lt;-</span> <span class="fu">dbConnect</span>(<span class="at">drv=</span>RSQLite<span class="sc">::</span><span class="fu">SQLite</span>(), <span class="at">dbname=</span><span class="st">"~/Library/Mobile Documents/com~apple~CloudDocs/M1 ECAP/R avancé/data/data.sqlite"</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>table <span class="ot">&lt;-</span> <span class="fu">dbListTables</span>(connexion)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="question-5" class="level3">
<h3 class="anchored" data-anchor-id="question-5">Question 5</h3>
<section id="créez-deux-nouvelles-tables-dans-la-base-de-données-à-laide-de-la-fonction-dbwritetable.-les-tables-sappeleront-respectivement-olympics_athletes-et-tokyo_athletes-pour-les-fichiers-olympics_athletes.json-et-tokyo_athletes.parquet." class="level4">
<h4 class="anchored" data-anchor-id="créez-deux-nouvelles-tables-dans-la-base-de-données-à-laide-de-la-fonction-dbwritetable.-les-tables-sappeleront-respectivement-olympics_athletes-et-tokyo_athletes-pour-les-fichiers-olympics_athletes.json-et-tokyo_athletes.parquet.">Créez deux nouvelles tables dans la base de données à l’aide de la fonction dbWriteTable. Les tables s’appeleront respectivement olympics_athletes et tokyo_athletes pour les fichiers olympics_athletes.json et tokyo_athletes.parquet.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">dbIsValid</span>(connexion)) {</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  file_olympics <span class="ot">&lt;-</span> <span class="st">"/Users/ameldahmani/Library/Mobile Documents/com~apple~CloudDocs/M1 ECAP/R avancé/data/olympics_athletes.json"</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  file_tokyo <span class="ot">&lt;-</span> <span class="st">"/Users/ameldahmani/Library/Mobile Documents/com~apple~CloudDocs/M1 ECAP/R avancé/data/tokyo_athletes.parquet"</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tryCatch</span>({</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Chargement des données json avec read_json</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>    data_olympics <span class="ot">&lt;-</span> <span class="fu">read_json</span>(file_olympics, <span class="at">simplifyVector =</span> <span class="cn">TRUE</span>)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>    <span class="co">#Convertion des données as.data.frame </span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>   </span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>   data_olympics_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(data_olympics)</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>    <span class="co">#dbWriteTable avec append=TRUE pour ajouter à la table déjà existante</span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dbWriteTable</span>(connexion, <span class="st">"olympics_athletes"</span>, data_olympics_df, <span class="at">append =</span> <span class="cn">TRUE</span>)</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>    <span class="co">#dbWriteTable avec overwrite=TRUE pour écraser la table existante</span></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dbWriteTable</span>(connexion, <span class="st">"tokyo_athletes"</span>, <span class="fu">read_parquet</span>(file_tokyo), <span class="at">overwrite =</span> <span class="cn">TRUE</span>)</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>  }, <span class="at">error =</span> <span class="cf">function</span>(e) {</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"Erreur lors de la lecture du fichier JSON :"</span>, <span class="fu">conditionMessage</span>(e), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>  })</span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Erreur, la connexion à la base de données a échoué."</span>)</span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Les deux tables ont bien été crées.</p>
</section>
</section>
<section id="question-6" class="level3">
<h3 class="anchored" data-anchor-id="question-6">Question 6</h3>
<section id="inspectez-la-table-olympics_athletes-en-utilisant-la-fonction-dblistfields.-quelles-sont-les-colonnes-de-la-table" class="level4">
<h4 class="anchored" data-anchor-id="inspectez-la-table-olympics_athletes-en-utilisant-la-fonction-dblistfields.-quelles-sont-les-colonnes-de-la-table">Inspectez la table olympics_athletes en utilisant la fonction dbListFields. Quelles sont les colonnes de la table ?</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">dbIsValid</span>(connexion)) {</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  colonnes_olympics <span class="ot">&lt;-</span> <span class="fu">dbListFields</span>(connexion, <span class="st">"olympics_athletes"</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(colonnes_olympics)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Erreur, la connexion à la base de données a échoué."</span>)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "ID"     "Name"   "Sex"    "Age"    "Height" "Weight" "Team"   "NOC"   
 [9] "Games"  "City"   "Sport"  "Event"  "Medal" </code></pre>
</div>
</div>
<p>Les colonnes de la table sont les suivantes :<br>
- ID<br>
- Name<br>
- Sex<br>
- Age<br>
- Height<br>
- Weight<br>
- Team<br>
- NOC<br>
- Games<br>
- City<br>
- Sport<br>
- Event<br>
- Medal</p>
</section>
</section>
<section id="question-7" class="level3">
<h3 class="anchored" data-anchor-id="question-7">Question 7</h3>
<section id="importez-cette-table-depuis-la-base-de-données-en-utilisant-la-fonction-dbreadtable." class="level4">
<h4 class="anchored" data-anchor-id="importez-cette-table-depuis-la-base-de-données-en-utilisant-la-fonction-dbreadtable.">Importez cette table depuis la base de données en utilisant la fonction dbReadTable.</h4>
</section>
<section id="convertissez-la-table-en-tibble-en-utilisant-la-fonction-as_tibble." class="level4">
<h4 class="anchored" data-anchor-id="convertissez-la-table-en-tibble-en-utilisant-la-fonction-as_tibble.">Convertissez la table en tibble en utilisant la fonction as_tibble.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">dbIsValid</span>(connexion)) {</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  nomdelatable <span class="ot">&lt;-</span> <span class="st">"olympics_athletes"</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  table_importee <span class="ot">&lt;-</span> <span class="fu">dbReadTable</span>(connexion, nomdelatable)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  tibbleresultat <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(table_importee)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(tibbleresultat)</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Erreur, la connexion à la base de données a échoué."</span>)</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,427,579 × 13
      ID Name      Sex     Age Height Weight Team  NOC   Games City  Sport Event
   &lt;int&gt; &lt;chr&gt;     &lt;chr&gt; &lt;int&gt;  &lt;int&gt;  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;
 1     1 A Dijiang M        24    180     80 China CHN   1992… Barc… Bask… Bask…
 2     2 A Lamusi  M        23    170     60 China CHN   2012… Lond… Judo  Judo…
 3     3 Gunnar N… M        24     NA     NA Denm… DEN   1920… Antw… Foot… Foot…
 4     4 Edgar Li… M        34     NA     NA Denm… DEN   1900… Paris Tug-… Tug-…
 5     5 Christin… F        21    185     82 Neth… NED   1988… Calg… Spee… Spee…
 6     5 Christin… F        21    185     82 Neth… NED   1988… Calg… Spee… Spee…
 7     5 Christin… F        25    185     82 Neth… NED   1992… Albe… Spee… Spee…
 8     5 Christin… F        25    185     82 Neth… NED   1992… Albe… Spee… Spee…
 9     5 Christin… F        27    185     82 Neth… NED   1994… Lill… Spee… Spee…
10     5 Christin… F        27    185     82 Neth… NED   1994… Lill… Spee… Spee…
# ℹ 2,427,569 more rows
# ℹ 1 more variable: Medal &lt;chr&gt;</code></pre>
</div>
</div>
</section>
</section>
<section id="dans-les-questions-suivantes-utilisez-en-priorité-les-fonctions-des-packages-dplyr-tidyr." class="level3">
<h3 class="anchored" data-anchor-id="dans-les-questions-suivantes-utilisez-en-priorité-les-fonctions-des-packages-dplyr-tidyr.">Dans les questions suivantes, utilisez en priorité les fonctions des packages dplyr, tidyr.</h3>
</section>
<section id="dplyr-tidyr" class="level3">
<h3 class="anchored" data-anchor-id="dplyr-tidyr">dplyr, tidyr</h3>
<section id="dans-les-questions-suivantes-utilisez-en-priorité-les-fonctions-des-packages-dplyr-tidyr.-1" class="level4">
<h4 class="anchored" data-anchor-id="dans-les-questions-suivantes-utilisez-en-priorité-les-fonctions-des-packages-dplyr-tidyr.-1">Dans les questions suivantes, utilisez en priorité les fonctions des packages dplyr, tidyr.</h4>
</section>
</section>
<section id="question-8" class="level3">
<h3 class="anchored" data-anchor-id="question-8">Question 8</h3>
<section id="convertissez-la-colonne-sex-en-variable-catégorielle-avec-la-fonction-mutate" class="level4">
<h4 class="anchored" data-anchor-id="convertissez-la-colonne-sex-en-variable-catégorielle-avec-la-fonction-mutate">Convertissez la colonne Sex en variable catégorielle avec la fonction mutate</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>tibbleresultat <span class="ot">&lt;-</span> tibbleresultat<span class="sc">|&gt;</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Sex =</span> <span class="fu">as.factor</span>(Sex))</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(tibbleresultat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,427,579 × 13
      ID Name      Sex     Age Height Weight Team  NOC   Games City  Sport Event
   &lt;int&gt; &lt;chr&gt;     &lt;fct&gt; &lt;int&gt;  &lt;int&gt;  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;
 1     1 A Dijiang M        24    180     80 China CHN   1992… Barc… Bask… Bask…
 2     2 A Lamusi  M        23    170     60 China CHN   2012… Lond… Judo  Judo…
 3     3 Gunnar N… M        24     NA     NA Denm… DEN   1920… Antw… Foot… Foot…
 4     4 Edgar Li… M        34     NA     NA Denm… DEN   1900… Paris Tug-… Tug-…
 5     5 Christin… F        21    185     82 Neth… NED   1988… Calg… Spee… Spee…
 6     5 Christin… F        21    185     82 Neth… NED   1988… Calg… Spee… Spee…
 7     5 Christin… F        25    185     82 Neth… NED   1992… Albe… Spee… Spee…
 8     5 Christin… F        25    185     82 Neth… NED   1992… Albe… Spee… Spee…
 9     5 Christin… F        27    185     82 Neth… NED   1994… Lill… Spee… Spee…
10     5 Christin… F        27    185     82 Neth… NED   1994… Lill… Spee… Spee…
# ℹ 2,427,569 more rows
# ℹ 1 more variable: Medal &lt;chr&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(tibbleresultat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [2,427,579 × 13] (S3: tbl_df/tbl/data.frame)
 $ ID    : int [1:2427579] 1 2 3 4 5 5 5 5 5 5 ...
 $ Name  : chr [1:2427579] "A Dijiang" "A Lamusi" "Gunnar Nielsen Aaby" "Edgar Lindenau Aabye" ...
 $ Sex   : Factor w/ 2 levels "F","M": 2 2 2 2 1 1 1 1 1 1 ...
 $ Age   : int [1:2427579] 24 23 24 34 21 21 25 25 27 27 ...
 $ Height: int [1:2427579] 180 170 NA NA 185 185 185 185 185 185 ...
 $ Weight: num [1:2427579] 80 60 NA NA 82 82 82 82 82 82 ...
 $ Team  : chr [1:2427579] "China" "China" "Denmark" "Denmark/Sweden" ...
 $ NOC   : chr [1:2427579] "CHN" "CHN" "DEN" "DEN" ...
 $ Games : chr [1:2427579] "1992 Summer" "2012 Summer" "1920 Summer" "1900 Summer" ...
 $ City  : chr [1:2427579] "Barcelona" "London" "Antwerpen" "Paris" ...
 $ Sport : chr [1:2427579] "Basketball" "Judo" "Football" "Tug-Of-War" ...
 $ Event : chr [1:2427579] "Basketball Men's Basketball" "Judo Men's Extra-Lightweight" "Football Men's Football" "Tug-Of-War Men's Tug-Of-War" ...
 $ Medal : chr [1:2427579] NA NA NA "Gold" ...</code></pre>
</div>
</div>
<p>La colonne Sex a bien été convertie en variable catégorielle.</p>
</section>
</section>
<section id="question-9" class="level3">
<h3 class="anchored" data-anchor-id="question-9">Question 9</h3>
<section id="créez-deux-colonnes-à-partir-de-la-colonne-games.-la-première-colonne-year-sera-une-colonne-de-type-integer-contenant-lannée-des-jeux.-la-deuxième-colonne-issummer-sera-une-colonne-booléenne-qui-indiquera-si-les-jeux-sont-des-jeux-dété-ou-dhiver.-vous-pourrez-utiliser-la-fonction-separate_wider_delim-de-tidyr-notamment" class="level4">
<h4 class="anchored" data-anchor-id="créez-deux-colonnes-à-partir-de-la-colonne-games.-la-première-colonne-year-sera-une-colonne-de-type-integer-contenant-lannée-des-jeux.-la-deuxième-colonne-issummer-sera-une-colonne-booléenne-qui-indiquera-si-les-jeux-sont-des-jeux-dété-ou-dhiver.-vous-pourrez-utiliser-la-fonction-separate_wider_delim-de-tidyr-notamment">Créez deux colonnes à partir de la colonne Games. La première colonne Year sera une colonne de type integer contenant l’année des jeux. La deuxième colonne isSummer sera une colonne booléenne qui indiquera si les jeux sont des jeux d’été ou d’hiver. Vous pourrez utiliser la fonction separate_wider_delim de tidyr notamment</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>tibbleresultat <span class="ot">&lt;-</span> tibbleresultat <span class="sc">|&gt;</span> </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(Games, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"Year"</span>, <span class="st">"isSummer"</span>), <span class="at">sep =</span> <span class="st">" "</span>, <span class="at">convert =</span> <span class="cn">TRUE</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(tibbleresultat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,427,579 × 14
      ID Name   Sex     Age Height Weight Team  NOC    Year isSummer City  Sport
   &lt;int&gt; &lt;chr&gt;  &lt;fct&gt; &lt;int&gt;  &lt;int&gt;  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;int&gt; &lt;chr&gt;    &lt;chr&gt; &lt;chr&gt;
 1     1 A Dij… M        24    180     80 China CHN    1992 Summer   Barc… Bask…
 2     2 A Lam… M        23    170     60 China CHN    2012 Summer   Lond… Judo 
 3     3 Gunna… M        24     NA     NA Denm… DEN    1920 Summer   Antw… Foot…
 4     4 Edgar… M        34     NA     NA Denm… DEN    1900 Summer   Paris Tug-…
 5     5 Chris… F        21    185     82 Neth… NED    1988 Winter   Calg… Spee…
 6     5 Chris… F        21    185     82 Neth… NED    1988 Winter   Calg… Spee…
 7     5 Chris… F        25    185     82 Neth… NED    1992 Winter   Albe… Spee…
 8     5 Chris… F        25    185     82 Neth… NED    1992 Winter   Albe… Spee…
 9     5 Chris… F        27    185     82 Neth… NED    1994 Winter   Lill… Spee…
10     5 Chris… F        27    185     82 Neth… NED    1994 Winter   Lill… Spee…
# ℹ 2,427,569 more rows
# ℹ 2 more variables: Event &lt;chr&gt;, Medal &lt;chr&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>tibbleresultat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,427,579 × 14
      ID Name   Sex     Age Height Weight Team  NOC    Year isSummer City  Sport
   &lt;int&gt; &lt;chr&gt;  &lt;fct&gt; &lt;int&gt;  &lt;int&gt;  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;int&gt; &lt;chr&gt;    &lt;chr&gt; &lt;chr&gt;
 1     1 A Dij… M        24    180     80 China CHN    1992 Summer   Barc… Bask…
 2     2 A Lam… M        23    170     60 China CHN    2012 Summer   Lond… Judo 
 3     3 Gunna… M        24     NA     NA Denm… DEN    1920 Summer   Antw… Foot…
 4     4 Edgar… M        34     NA     NA Denm… DEN    1900 Summer   Paris Tug-…
 5     5 Chris… F        21    185     82 Neth… NED    1988 Winter   Calg… Spee…
 6     5 Chris… F        21    185     82 Neth… NED    1988 Winter   Calg… Spee…
 7     5 Chris… F        25    185     82 Neth… NED    1992 Winter   Albe… Spee…
 8     5 Chris… F        25    185     82 Neth… NED    1992 Winter   Albe… Spee…
 9     5 Chris… F        27    185     82 Neth… NED    1994 Winter   Lill… Spee…
10     5 Chris… F        27    185     82 Neth… NED    1994 Winter   Lill… Spee…
# ℹ 2,427,569 more rows
# ℹ 2 more variables: Event &lt;chr&gt;, Medal &lt;chr&gt;</code></pre>
</div>
</div>
<p>Les colonnes Year et isSummer ont bien été crées.</p>
</section>
<section id="les-questions-suivantes-nécessitent-lapplication-de-plusieurs-instructions-en-séquence.-essayez-tant-que-possible-de-chaîner-les-instructions-avec-des-pipes-ou-." class="level4">
<h4 class="anchored" data-anchor-id="les-questions-suivantes-nécessitent-lapplication-de-plusieurs-instructions-en-séquence.-essayez-tant-que-possible-de-chaîner-les-instructions-avec-des-pipes-ou-.">Les questions suivantes nécessitent l’application de plusieurs instructions en séquence. Essayez tant que possible de chaîner les instructions avec des pipes (%&gt;% ou |&gt;).</h4>
</section>
</section>
<section id="question-10" class="level3">
<h3 class="anchored" data-anchor-id="question-10">Question 10</h3>
<section id="calculez-la-moyenne-dage-des-athletes-pour-chacune-des-éditions-des-jo-dété.-quelle-édition-a-compté-les-athlètes-les-plus-jeunes-les-plus-vieux" class="level4">
<h4 class="anchored" data-anchor-id="calculez-la-moyenne-dage-des-athletes-pour-chacune-des-éditions-des-jo-dété.-quelle-édition-a-compté-les-athlètes-les-plus-jeunes-les-plus-vieux">Calculez la moyenne d’age des athletes pour chacune des éditions des JO d’été. Quelle édition a compté les athlètes les plus jeunes ? Les plus vieux ?</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>Moyenne_age <span class="ot">&lt;-</span> tibbleresultat <span class="sc">|&gt;</span> </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year) <span class="sc">|&gt;</span> </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">moyenne_age =</span> <span class="fu">mean</span>(Age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(Moyenne_age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 35 × 2
    Year moyenne_age
   &lt;int&gt;       &lt;dbl&gt;
 1  1896        23.6
 2  1900        28.9
 3  1904        26.7
 4  1906        27.1
 5  1908        27.0
 6  1912        27.5
 7  1920        29.3
 8  1924        28.0
 9  1928        27.9
10  1932        29.6
# ℹ 25 more rows</code></pre>
</div>
</div>
<section id="athlètes-les-plus-jeunes" class="level5">
<h5 class="anchored" data-anchor-id="athlètes-les-plus-jeunes">Athlètes les plus jeunes</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>plusjeunes <span class="ot">&lt;-</span> Moyenne_age <span class="sc">|&gt;</span> </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(moyenne_age <span class="sc">==</span> <span class="fu">min</span>(moyenne_age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(plusjeunes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
   Year moyenne_age
  &lt;int&gt;       &lt;dbl&gt;
1  1896        23.6</code></pre>
</div>
</div>
<p>L’édition de 1896 a présenté les athlètes les plus jeunes, avec une moyenne d’âge de 23,6 ans.</p>
</section>
<section id="athlètes-les-plus-vieux" class="level5">
<h5 class="anchored" data-anchor-id="athlètes-les-plus-vieux">Athlètes les plus vieux</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>plusvieux <span class="ot">&lt;-</span> Moyenne_age <span class="sc">|&gt;</span>  </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(moyenne_age <span class="sc">==</span> <span class="fu">max</span>(moyenne_age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(plusvieux)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
   Year moyenne_age
  &lt;int&gt;       &lt;dbl&gt;
1  1932        29.6</code></pre>
</div>
</div>
<p>L’édition de 1932 a accueilli les athlètes les plus âgés, avec une moyenne d’âge de 29,6 ans.</p>
</section>
</section>
</section>
<section id="question-11" class="level3">
<h3 class="anchored" data-anchor-id="question-11">Question 11</h3>
<section id="quelle-est-la-discipline-des-jo-dété-dont-la-taille-des-athlètes-féminines-est-la-plus-grande-quelle-a-été-cette-discipline-au-cours-de-chacune-des-éditions-calculez-le-nombre-de-fois-où-chaque-discipline-a-été-la-discipline-avec-les-plus-grandes-athlètes" class="level4">
<h4 class="anchored" data-anchor-id="quelle-est-la-discipline-des-jo-dété-dont-la-taille-des-athlètes-féminines-est-la-plus-grande-quelle-a-été-cette-discipline-au-cours-de-chacune-des-éditions-calculez-le-nombre-de-fois-où-chaque-discipline-a-été-la-discipline-avec-les-plus-grandes-athlètes">Quelle est la discipline des JO d’été dont la taille des athlètes féminines est la plus grande? Quelle a été cette discipline au cours de chacune des éditions ? Calculez le nombre de fois où chaque discipline a été la discipline avec les plus grandes athlètes</h4>
<section id="méthode-1" class="level5">
<h5 class="anchored" data-anchor-id="méthode-1">méthode 1</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>athletes_femmes <span class="ot">&lt;-</span> tibbleresultat <span class="sc">|&gt;</span> </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Sex <span class="sc">==</span> <span class="st">"F"</span>)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>athletes_femmes <span class="ot">&lt;-</span> athletes_femmes <span class="sc">|&gt;</span> </span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Height =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(Height), <span class="dv">0</span>, Height))</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>plus_grande_taille_par_discipline <span class="ot">&lt;-</span> athletes_femmes <span class="sc">|&gt;</span> </span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Sport, Year, <span class="at">.groups =</span> <span class="st">"drop_last"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">taille_max =</span> <span class="fu">max</span>(Height, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">"drop_last"</span>)</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>plus_grande_taille_discipline_par_annee <span class="ot">&lt;-</span> plus_grande_taille_par_discipline <span class="sc">|&gt;</span> </span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year, <span class="at">.groups =</span> <span class="st">"drop_last"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(taille_max <span class="sc">==</span> <span class="fu">max</span>(taille_max, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), .groups <span class="sc">==</span> <span class="st">"drop_last"</span>)</span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>discipline_plus_grande_frequence <span class="ot">&lt;-</span> plus_grande_taille_discipline_par_annee <span class="sc">|&gt;</span> </span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Sport, <span class="at">.groups =</span> <span class="st">"drop_last"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">frequence =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">"drop_last"</span>)</span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Discipline des JO d'été avec la plus grande taille d'athlètes féminines par année :"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Discipline des JO d'été avec la plus grande taille d'athlètes féminines par année :"</code></pre>
</div>
</div>
</section>
<section id="méthode-2" class="level5">
<h5 class="anchored" data-anchor-id="méthode-2">méthode 2</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>discipline_plus_grande_frequence2 <span class="ot">&lt;-</span> plus_grande_taille_discipline_par_annee <span class="sc">|&gt;</span> </span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Sport) <span class="sc">|&gt;</span> </span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">frequence =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span> </span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(frequence)) <span class="sc">|&gt;</span> </span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>La deuxième méthode permet de classer les disciplines par fréquence, assurant ainsi que la discipline la plus fréquente apparaîtra en premier.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(plus_grande_taille_discipline_par_annee, <span class="at">n =</span> <span class="dv">60</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 48 × 4
# Groups:   Year, .groups [34]
   Sport           Year .groups   taille_max
   &lt;chr&gt;          &lt;int&gt; &lt;chr&gt;          &lt;dbl&gt;
 1 Archery         1904 drop_last          0
 2 Archery         1908 drop_last          0
 3 Athletics       1948 drop_last        180
 4 Athletics       1952 drop_last        188
 5 Athletics       1956 drop_last        185
 6 Athletics       1964 drop_last        188
 7 Athletics       1968 drop_last        188
 8 Athletics       1972 drop_last        190
 9 Basketball      1976 drop_last        210
10 Basketball      1980 drop_last        210
11 Basketball      1984 drop_last        205
12 Basketball      1988 drop_last        204
13 Basketball      1992 drop_last        204
14 Basketball      1996 drop_last        204
15 Basketball      2000 drop_last        213
16 Basketball      2004 drop_last        202
17 Basketball      2008 drop_last        202
18 Basketball      2012 drop_last        206
19 Basketball      2016 drop_last        203
20 Bobsleigh       2002 drop_last        187
21 Bobsleigh       2006 drop_last        187
22 Bobsleigh       2010 drop_last        194
23 Croquet         1900 drop_last          0
24 Diving          1912 drop_last          0
25 Diving          1920 drop_last        175
26 Equestrianism   1900 drop_last          0
27 Fencing         1924 drop_last        175
28 Fencing         1928 drop_last        183
29 Fencing         1932 drop_last        183
30 Fencing         1936 drop_last        183
31 Figure Skating  1908 drop_last          0
32 Golf            1900 drop_last          0
33 Ice Hockey      2014 drop_last        186
34 Luge            1994 drop_last        187
35 Luge            1998 drop_last        187
36 Motorboating    1908 drop_last          0
37 Sailing         1900 drop_last          0
38 Sailing         1908 drop_last          0
39 Swimming        1912 drop_last          0
40 Swimming        1960 drop_last        186
41 Tennis          1900 drop_last          0
42 Tennis          1906 drop_last          0
43 Tennis          1908 drop_last          0
44 Tennis          1912 drop_last          0
45 Tennis          1924 drop_last        175
46 Volleyball      1964 drop_last        188
47 Volleyball      2004 drop_last        202
48 Volleyball      2008 drop_last        202</code></pre>
</div>
</div>
<p>La plus grande taille par discipline est observée dans le basketball, atteignant 213 cm.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(discipline_plus_grande_frequence)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 17 × 3
# Groups:   Sport [17]
   Sport          .groups   frequence
   &lt;chr&gt;          &lt;chr&gt;         &lt;int&gt;
 1 Archery        drop_last         2
 2 Athletics      drop_last         6
 3 Basketball     drop_last        11
 4 Bobsleigh      drop_last         3
 5 Croquet        drop_last         1
 6 Diving         drop_last         2
 7 Equestrianism  drop_last         1
 8 Fencing        drop_last         4
 9 Figure Skating drop_last         1
10 Golf           drop_last         1
11 Ice Hockey     drop_last         1
12 Luge           drop_last         2
13 Motorboating   drop_last         1
14 Sailing        drop_last         2
15 Swimming       drop_last         2
16 Tennis         drop_last         5
17 Volleyball     drop_last         3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(discipline_plus_grande_frequence2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 17 × 2
   Sport          frequence
   &lt;chr&gt;              &lt;int&gt;
 1 Basketball            11
 2 Athletics              6
 3 Tennis                 5
 4 Fencing                4
 5 Bobsleigh              3
 6 Volleyball             3
 7 Archery                2
 8 Diving                 2
 9 Luge                   2
10 Sailing                2
11 Swimming               2
12 Croquet                1
13 Equestrianism          1
14 Figure Skating         1
15 Golf                   1
16 Ice Hockey             1
17 Motorboating           1</code></pre>
</div>
</div>
<p>Sur l’ensemble des éditions, le basketball a été la discipline avec les plus grandes athlètes féminines à 11 reprises.</p>
</section>
</section>
</section>
<section id="vous-disposez-du-texte-suivant" class="level3">
<h3 class="anchored" data-anchor-id="vous-disposez-du-texte-suivant">Vous disposez du texte suivant :</h3>
<section id="les-jeux-olympiques-dété-se-déroulent-normalement-tous-les-4-ans-durant-les-mois-de-juillet-et-août.-les-jeux-de-rio-ont-eu-lieu-du-5-août-2016-au-20-août-2016-ceux-de-tokyo-du-23-juillet-2021-au-8-août-2021-et-ceux-de-paris-auront-lieu-du-26-juillet-2024-au-11-août-2024.-plus-de-10000-athlètes-sont-attendus-du-monde-entier-à-paris." class="level6">
<h6 class="anchored" data-anchor-id="les-jeux-olympiques-dété-se-déroulent-normalement-tous-les-4-ans-durant-les-mois-de-juillet-et-août.-les-jeux-de-rio-ont-eu-lieu-du-5-août-2016-au-20-août-2016-ceux-de-tokyo-du-23-juillet-2021-au-8-août-2021-et-ceux-de-paris-auront-lieu-du-26-juillet-2024-au-11-août-2024.-plus-de-10000-athlètes-sont-attendus-du-monde-entier-à-paris.">Les jeux olympiques d’été se déroulent normalement tous les 4 ans, durant les mois de Juillet et Août. Les jeux de Rio ont eu lieu du 5 Août 2016 au 20 Août 2016, ceux de Tokyo du 23 Juillet 2021 au 8 Août 2021, et ceux de Paris auront lieu du 26 Juillet 2024 au 11 Août 2024. Plus de 10000 athlètes sont attendus du monde entier à Paris.</h6>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>texte <span class="ot">&lt;-</span> <span class="st">"Les jeux olympiques d’été se déroulent normalement tous les 4 ans, durant les mois de Juillet et Août. Les jeux de Rio ont eu lieu du 5 Août 2016 au 20 Août 2016, ceux de Tokyo du 23 Juillet 2021 au 8 Août 2021, et ceux de Paris auront lieu du 26 Juillet 2024 au 11 Août 2024. Plus de 10000 athlètes sont attendus du monde entier à Paris."</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="stringr-lubridate" class="level3">
<h3 class="anchored" data-anchor-id="stringr-lubridate">stringr, lubridate</h3>
<div style="text-align: justify;">
<p>Vous disposez du texte suivant :</p>
<p>Les jeux olympiques d’été se déroulent normalement tous les 4 ans, durant les mois de Juillet et Août. Les jeux de Rio ont eu lieu du 5 Août 2016 au 20 Août 2016, ceux de Tokyo du 23 Juillet 2021 au 8 Août 2021, et ceux de Paris auront lieu du 26 Juillet 2024 au 11 Août 2024. Plus de 10000 athlètes sont attendus du monde entier à Paris.</p>
</div>
</section>
<section id="question-12" class="level3">
<h3 class="anchored" data-anchor-id="question-12">Question 12</h3>
<section id="en-utilisant-les-fonctions-du-packages-stringr-extrayez-les-dates-des-différentes-éditions-des-jo.-aide-définissez-une-expression-régulière-capable-de-capturer-une-séquence-de-caractères-représentant-une-date-telle-que-26-juillet-2024.-vous-pourrez-utiliser-cette-regex-avec-la-fonction-str_extract_all-par-exemple." class="level4" style="text-align: justify;">
<h4 class="anchored" data-anchor-id="en-utilisant-les-fonctions-du-packages-stringr-extrayez-les-dates-des-différentes-éditions-des-jo.-aide-définissez-une-expression-régulière-capable-de-capturer-une-séquence-de-caractères-représentant-une-date-telle-que-26-juillet-2024.-vous-pourrez-utiliser-cette-regex-avec-la-fonction-str_extract_all-par-exemple.">En utilisant les fonctions du packages stringr, extrayez les dates des différentes éditions des JO. Aide : définissez une expression régulière capable de capturer une séquence de caractères représentant une date telle que “26 Juillet 2024”. Vous pourrez utiliser cette regex avec la fonction str_extract_all par exemple.</h4>
</section>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>format_date <span class="ot">&lt;-</span> <span class="st">"</span><span class="sc">\\</span><span class="st">b</span><span class="sc">\\</span><span class="st">d{1,2} (Janvier|Février|Mars|Avril|Mai|Juin|Juillet|Août|Septembre|Octobre|Novembre|Décembre) </span><span class="sc">\\</span><span class="st">d{4}</span><span class="sc">\\</span><span class="st">b"</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>datesJO <span class="ot">&lt;-</span> <span class="fu">str_extract_all</span>(texte, format_date)[[<span class="dv">1</span>]]</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(datesJO)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "5 Août 2016"     "20 Août 2016"    "23 Juillet 2021" "8 Août 2021"    
[5] "26 Juillet 2024" "11 Août 2024"   </code></pre>
</div>
</div>
<p>Les dates mentionnées ci-dessus correspondent aux différentes éditions des Jeux Olympiques.</p>
</section>
<section id="question-13" class="level3">
<h3 class="anchored" data-anchor-id="question-13">Question 13</h3>
<section id="remplacez-les-noms-des-mois-par-leur-numéro-pour-rendre-ces-éléments-convertibles-en-date-en-utilisant-la-fonction-str_replace" class="level4">
<h4 class="anchored" data-anchor-id="remplacez-les-noms-des-mois-par-leur-numéro-pour-rendre-ces-éléments-convertibles-en-date-en-utilisant-la-fonction-str_replace">Remplacez les noms des mois par leur numéro pour rendre ces éléments convertibles en date en utilisant la fonction str_replace</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>mois_num <span class="ot">&lt;-</span> <span class="cf">function</span>(mois) {</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  mois <span class="ot">&lt;-</span> <span class="fu">tolower</span>(mois)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  mois_num <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"janvier"</span>, <span class="st">"février"</span>, <span class="st">"mars"</span>, <span class="st">"avril"</span>, <span class="st">"mai"</span>, <span class="st">"juin"</span>, <span class="st">"juillet"</span>, <span class="st">"août"</span>, <span class="st">"septembre"</span>, <span class="st">"octobre"</span>, <span class="st">"novembre"</span>, <span class="st">"décembre"</span>)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">match</span>(mois, mois_num))</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>dates_num <span class="ot">&lt;-</span> <span class="fu">str_replace_all</span>(datesJO, format_date, <span class="cf">function</span>(match) {</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>  elements <span class="ot">&lt;-</span> <span class="fu">str_split</span>(match, <span class="st">" "</span>)[[<span class="dv">1</span>]]</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>  elements[<span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="fu">mois_num</span>(elements[<span class="dv">2</span>])</span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">paste</span>(elements, <span class="at">collapse =</span> <span class="st">" "</span>))</span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(dates_num)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "5 8 2016"  "20 8 2016" "23 7 2021" "8 8 2021"  "26 7 2024" "11 8 2024"</code></pre>
</div>
</div>
<p>Le remplacement des noms des mois par leur numéro a bien fonctionné.</p>
</section>
</section>
<section id="question-14" class="level3">
<h3 class="anchored" data-anchor-id="question-14">Question 14</h3>
<section id="convertissez-ces-3-éléments-en-date-en-utilisant-la-fonction-appropriée-du-package-lubridate" class="level4">
<h4 class="anchored" data-anchor-id="convertissez-ces-3-éléments-en-date-en-utilisant-la-fonction-appropriée-du-package-lubridate">Convertissez ces 3 éléments en date en utilisant la fonction appropriée du package lubridate</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>convertion <span class="ot">&lt;-</span> <span class="cf">function</span>(date_texte) {</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  elements <span class="ot">&lt;-</span> <span class="fu">str_split</span>(date_texte, <span class="st">" "</span>)[[<span class="dv">1</span>]]</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  jour <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(elements[<span class="dv">1</span>])</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  mois <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(elements[<span class="dv">2</span>])</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>  annee <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(elements[<span class="dv">3</span>])</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">dmy</span>(<span class="fu">paste</span>(jour, mois, annee, <span class="at">sep =</span> <span class="st">"-"</span>)))</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>dates_converties <span class="ot">&lt;-</span> <span class="fu">sapply</span>(dates_num, convertion)</span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>dates_converties</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> 5 8 2016 20 8 2016 23 7 2021  8 8 2021 26 7 2024 11 8 2024 
    17018     17033     18831     18847     19930     19946 </code></pre>
</div>
</div>
<p>La conversion a également bien fonctionné.</p>
</section>
</section>
<section id="question-15" class="level3">
<h3 class="anchored" data-anchor-id="question-15">Question 15</h3>
<section id="combien-de-jours-ont-séparés-les-éditions-de-rio-et-tokyo" class="level4">
<h4 class="anchored" data-anchor-id="combien-de-jours-ont-séparés-les-éditions-de-rio-et-tokyo">Combien de jours ont séparés les éditions de Rio et Tokyo ?</h4>
</section>
<section id="et-sépareront-les-éditions-de-tokyo-et-de-paris-faites-le-même-calcul-en-semaines." class="level4">
<h4 class="anchored" data-anchor-id="et-sépareront-les-éditions-de-tokyo-et-de-paris-faites-le-même-calcul-en-semaines.">Et sépareront les éditions de Tokyo et de Paris ? Faites le même calcul en semaines.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>ParisDate <span class="ot">&lt;-</span> <span class="fu">dmy</span>(<span class="st">"26 Juillet 2024"</span>, <span class="at">locale =</span> <span class="st">"fr_FR"</span>)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>TokyoDate <span class="ot">&lt;-</span> <span class="fu">dmy</span>(<span class="st">"23 Juillet 2021"</span>, <span class="at">locale =</span> <span class="st">"fr_FR"</span>)</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>RioDate <span class="ot">&lt;-</span> <span class="fu">dmy</span>(<span class="st">"5 Août 2016"</span>, <span class="at">locale =</span> <span class="st">"fr_FR"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="jours-qui-séparent-rio-et-tokyo" class="level5">
<h5 class="anchored" data-anchor-id="jours-qui-séparent-rio-et-tokyo">Jours qui séparent Rio et Tokyo</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>Rio_Tokyo_jours <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">difftime</span>(TokyoDate, RioDate, <span class="at">units =</span> <span class="st">"days"</span>))</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Nombre de jours entre Rio et Tokyo :"</span>, Rio_Tokyo_jours, <span class="st">"jours</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Nombre de jours entre Rio et Tokyo : 1813 jours</code></pre>
</div>
</div>
<p>1 813 jours séparent les éditions de Rio en 2016 et de Tokyo en 2021.</p>
</section>
<section id="jours-qui-séparent-tokyo-et-paris" class="level5">
<h5 class="anchored" data-anchor-id="jours-qui-séparent-tokyo-et-paris">Jours qui séparent Tokyo et Paris</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>Tokyo_Paris_jours <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">difftime</span>(ParisDate, TokyoDate, <span class="at">units =</span> <span class="st">"days"</span>))</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Nombre de jours entre Tokyo et Paris :"</span>, Tokyo_Paris_jours, <span class="st">"jours</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Nombre de jours entre Tokyo et Paris : 1099 jours</code></pre>
</div>
</div>
<p>1 099 jours séparent les éditions de Tokyo en 2021 et de Paris en 2024.</p>
</section>
<section id="semaines-qui-séparent-rio-et-tokyo" class="level5">
<h5 class="anchored" data-anchor-id="semaines-qui-séparent-rio-et-tokyo">Semaines qui séparent Rio et Tokyo</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>Rio_Tokyo_semaines <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">difftime</span>(TokyoDate, RioDate, <span class="at">units =</span> <span class="st">"weeks"</span>))</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Nombre de semaines entre Rio et Tokyo :"</span>, Rio_Tokyo_semaines, <span class="st">"semaines</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Nombre de semaines entre Rio et Tokyo : 259 semaines</code></pre>
</div>
</div>
<p>259 semaines séparent les éditions de Rio en 2016 et de Tokyo en 2021.</p>
</section>
<section id="jours-qui-séparent-tokyo-et-paris-1" class="level5">
<h5 class="anchored" data-anchor-id="jours-qui-séparent-tokyo-et-paris-1">Jours qui séparent Tokyo et Paris</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>Tokyo_Paris_semaines <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">difftime</span>(ParisDate, TokyoDate, <span class="at">units =</span> <span class="st">"weeks"</span>))</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Nombre de semaines entre Tokyo et Paris :"</span>, Tokyo_Paris_semaines, <span class="st">"semaines</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Nombre de semaines entre Tokyo et Paris : 157 semaines</code></pre>
</div>
</div>
<p>157 semaines séparent les éditions de Tokyo en 2021 et de Paris en 2024.</p>


</section>
</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>